# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DMKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DMKit

  pod 'MBProgressHUD'     , '~> 1.1.0'
  pod 'AFNetworking'      , '~> 3.2.1'
  pod 'Masonry'           , '~> 1.1.0'
  pod 'Toast'             , '~> 4.0.0'
  pod 'SDWebImage'        , '~> 5.1.0'
  
end
